version: '3'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      PG_DATABASE_URL: postgresql://postgres:postgres@db:5432/devdb
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"

volumes:
  postgres_data: