version: '3'

services:
  api_server:
    build:
      context: .
    ports: 
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: >
      sh -c "uvicorn backend.main:app --reload"
#     environment:
#       - DB_HOST=db
#       - DB_NAME=dbname
#       - DB_USER=dbuser
#       - DB_PASS=changethis
#     depends_on:
#       - db
  
#   db:
#     image: postgres:alpine
#     volumes:
#       - dev-db-data:/var/lin/postgres/data
#     environment:
#       - POSTGRES_DB=dbname
#       - POSTGRES_USER=dbuser
#       - POSTGRES_PASSWORD=changethis

# volumes:
#   dev-db-data:
