---
name: Checks

on:
  push:
    branches:
      - master # or main
  
jobs:
  test:
    name: Test Api
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Checkout
        uses: actions/checkout/@v2
      - name: Test
        run: echo "simulating test"
